// Generated by tuning.fit_policy from measured passing runs.
// samples=216 metric=p50_call_ms max_depth=3
#pragma once


namespace bmms {

inline TilingKey SelectSubmissionTilingKey(
        const Shape& shape, int64_t availableCoreNum, int32_t inputDtype,
        bool transposeX1, bool transposeX2) {
    (void)shape;
    (void)availableCoreNum;
    (void)inputDtype;
    (void)transposeX1;
    (void)transposeX2;
    if (shape.n <= 33ULL) {
        if (static_cast<uint64_t>(shape.b) * shape.m <= 66ULL) {
            if (shape.k <= 32ULL) {
                return TilingKey::BM_64X128X128;
            } else {
                return TilingKey::BM_16X128X64;
            }
        } else {
            if (shape.k <= 72ULL) {
                return TilingKey::BM_64X128X128;
            } else {
                return TilingKey::BM_32X128X64;
            }
        }
    } else {
        if (shape.m <= 127ULL) {
            if (shape.n <= 65ULL) {
                return TilingKey::BM_16X128X64;
            } else {
                return TilingKey::BMN_16X256X64_P4;
            }
        } else {
            if (shape.b <= 1ULL) {
                return TilingKey::BM_16X128X64;
            } else {
                return TilingKey::BM_32X128X64;
            }
        }
    }
}

}  // namespace bmms
