// Generated by scripts/generate_tiling_catalog.py. Do not edit.
#pragma once
#include <cstddef>
#include <cstdint>

namespace bmms {

enum class TilingKey : uint32_t {
    VECTOR_REFERENCE = 0,
    BM_16X128X64 = 100,
    BM_32X128X64 = 101,
    BM_32X256X64 = 102,
    BM_64X128X128 = 103,
    BMN_16X256X64_P2 = 200,
    BMN_16X256X64_P4 = 201,
};

enum class KernelPath : uint8_t { REFERENCE, BM, BMN };

struct StaticTilingConfig {
    TilingKey key;
    const char* name;
    KernelPath path;
    bool implemented;
    uint32_t tileM;
    uint32_t tileN;
    uint32_t tileK;
    uint32_t vecM;
    uint32_t vecN;
    uint32_t splitN;
};

constexpr StaticTilingConfig kTilingConfigs[] = {
    {TilingKey::VECTOR_REFERENCE, "vector_reference", KernelPath::REFERENCE, true, 1, 1, 1, 1, 1, 1},
    {TilingKey::BM_16X128X64, "bm_16x128x64", KernelPath::BM, true, 16, 128, 64, 16, 128, 1},
    {TilingKey::BM_32X128X64, "bm_32x128x64", KernelPath::BM, true, 32, 128, 64, 32, 128, 1},
    {TilingKey::BM_32X256X64, "bm_32x256x64", KernelPath::BM, false, 32, 256, 64, 32, 128, 1},
    {TilingKey::BM_64X128X128, "bm_64x128x128", KernelPath::BM, false, 64, 128, 128, 32, 128, 1},
    {TilingKey::BMN_16X256X64_P2, "bmn_16x256x64_p2", KernelPath::BMN, true, 16, 256, 64, 16, 128, 2},
    {TilingKey::BMN_16X256X64_P4, "bmn_16x256x64_p4", KernelPath::BMN, true, 16, 256, 64, 16, 128, 4},
};

constexpr size_t kTilingConfigCount =
    sizeof(kTilingConfigs) / sizeof(kTilingConfigs[0]);

}  // namespace bmms
