// Generated by scripts/generate_tiling_catalog.py. Do not edit.
#pragma once
#include <cstddef>
#include <cstdint>

namespace bmms {

enum class TilingKey : uint32_t {
    VECTOR_REFERENCE = 0,
    AUTO_MATMUL_FUSED = 100,
    AUTO_MATMUL_FUSED_VECTOR = 110,
    AUTO_MATMUL_FUSED_ASYNC = 120,
    AUTO_MATMUL_FUSED_ASYNC_DB = 121,
    AUTO_MATMUL_FUSED_SPLIT_N = 130,
};

enum class KernelPath : uint8_t { REFERENCE, AUTO_FUSED };
enum class MatmulSchedule : uint8_t { SYNC, ASYNC };
enum class ReductionMode : uint8_t { SCALAR, VECTOR };

struct StaticTilingConfig {
    TilingKey key;
    const char* name;
    KernelPath path;
    MatmulSchedule schedule;
    ReductionMode reduction;
    uint32_t ubInputBuffers;
    bool implemented;
    uint32_t tileM;
    uint32_t tileN;
    uint32_t tileK;
    uint32_t vecM;
    uint32_t vecN;
    uint32_t splitN;
};

constexpr StaticTilingConfig kTilingConfigs[] = {
    {TilingKey::VECTOR_REFERENCE, "vector_reference", KernelPath::REFERENCE, MatmulSchedule::SYNC, ReductionMode::SCALAR, 1, true, 1, 1, 1, 1, 1, 1},
    {TilingKey::AUTO_MATMUL_FUSED, "auto_matmul_fused", KernelPath::AUTO_FUSED, MatmulSchedule::SYNC, ReductionMode::SCALAR, 1, true, 64, 128, 64, 32, 128, 1},
    {TilingKey::AUTO_MATMUL_FUSED_VECTOR, "auto_matmul_fused_vector", KernelPath::AUTO_FUSED, MatmulSchedule::SYNC, ReductionMode::VECTOR, 1, true, 64, 128, 64, 32, 128, 1},
    {TilingKey::AUTO_MATMUL_FUSED_ASYNC, "auto_matmul_fused_async", KernelPath::AUTO_FUSED, MatmulSchedule::ASYNC, ReductionMode::VECTOR, 1, true, 64, 128, 64, 32, 128, 1},
    {TilingKey::AUTO_MATMUL_FUSED_ASYNC_DB, "auto_matmul_fused_async_db", KernelPath::AUTO_FUSED, MatmulSchedule::ASYNC, ReductionMode::VECTOR, 2, true, 64, 128, 64, 32, 128, 1},
    {TilingKey::AUTO_MATMUL_FUSED_SPLIT_N, "auto_matmul_fused_split_n", KernelPath::AUTO_FUSED, MatmulSchedule::ASYNC, ReductionMode::VECTOR, 2, true, 64, 128, 64, 32, 128, 2},
};

constexpr size_t kTilingConfigCount =
    sizeof(kTilingConfigs) / sizeof(kTilingConfigs[0]);

}  // namespace bmms
