// Generated by scripts/generate_tiling_catalog.py. Do not edit.
#pragma once
#include <cstddef>
#include <cstdint>

namespace bmms {

enum class TilingKey : uint32_t {
    VECTOR_REFERENCE = 0,
    AUTO_MATMUL_FUSED = 100,
};

enum class KernelPath : uint8_t { REFERENCE, AUTO_FUSED };

struct StaticTilingConfig {
    TilingKey key;
    const char* name;
    KernelPath path;
    bool implemented;
    uint32_t tileM;
    uint32_t tileN;
    uint32_t tileK;
    uint32_t vecM;
    uint32_t vecN;
    uint32_t splitN;
};

constexpr StaticTilingConfig kTilingConfigs[] = {
    {TilingKey::VECTOR_REFERENCE, "vector_reference", KernelPath::REFERENCE, true, 1, 1, 1, 1, 1, 1},
    {TilingKey::AUTO_MATMUL_FUSED, "auto_matmul_fused", KernelPath::AUTO_FUSED, true, 64, 128, 64, 32, 128, 1},
};

constexpr size_t kTilingConfigCount =
    sizeof(kTilingConfigs) / sizeof(kTilingConfigs[0]);

}  // namespace bmms
