param(
    [string]$ProjectRoot = (Split-Path -Parent $PSScriptRoot),
    [string]$OutputPath = (Join-Path (Split-Path -Parent $PSScriptRoot) "submission/kernel.asc")
)

$ErrorActionPreference = "Stop"

$fragments = @(
    "tiling/tiling_catalog_generated.h",
    "tiling/tiling_types.h",
    "tiling/tiling_catalog.h",
    "host/acl_runtime.h",
    "host/input_validation.h",
    "host/fused_tiling.h",
    "tiling/tiling_policy.h",
    "kernels/reference/kernel.asc",
    "kernels/matmul_api/split_n_reduce.asc",
    "kernels/matmul_api/class_header.inc",
    "kernels/matmul_api/init.inc",
    "kernels/matmul_api/process.inc",
    "kernels/matmul_api/row_max.inc",
    "kernels/matmul_api/synchronous_tiles.inc",
    "kernels/matmul_api/asynchronous_tiles.inc",
    "kernels/matmul_api/tile_reduction.inc",
    "kernels/matmul_api/lane_sum.inc",
    "kernels/matmul_api/partial_max_and_state.inc",
    "kernels/matmul_api/launch.inc",
    "kernels/dispatch/resources.inc",
    "kernels/dispatch/reference_plan.inc",
    "kernels/dispatch/auto_plan.inc",
    "kernels/dispatch/split_n_plan.inc",
    "kernels/dispatch/execute_plan.inc",
    "kernel.asc"
)

$preamble = @'
// Self-contained competition submission bundle.
// Generated by scripts/bundle_submission.ps1; edit the modular sources instead.
#include <algorithm>
#include <cstddef>
#include <cstdint>
#include <atomic>
#include <stdexcept>
#include <string>
#include <vector>
#include "acl/acl.h"
#include "kernel_operator.h"
#include "tiling/tiling_api.h"
#include "tiling/platform/platform_ascendc.h"
'@

$sections = [System.Collections.Generic.List[string]]::new()
$sections.Add($preamble.TrimEnd())

foreach ($relativePath in $fragments) {
    $sourcePath = Join-Path $ProjectRoot $relativePath
    if (-not (Test-Path -LiteralPath $sourcePath -PathType Leaf)) {
        throw "Missing source fragment: $sourcePath"
    }

    $lines = Get-Content -LiteralPath $sourcePath
    $body = [System.Collections.Generic.List[string]]::new()
    $skipLocalTuningEntry = $false
    foreach ($line in $lines) {
        if ($relativePath -eq "kernel.asc" -and
            $line -match '^\s*#ifdef\s+BMMS_ENABLE_TUNING\s*$') {
            $skipLocalTuningEntry = $true
            continue
        }
        if ($skipLocalTuningEntry) {
            if ($line -match '^\s*#endif\s*$') {
                $skipLocalTuningEntry = $false
            }
            continue
        }
        if ($line -match '^\s*#pragma\s+once\s*$') {
            continue
        }
        if ($relativePath -eq "tiling/tiling_policy.h" -and
            $line -match '^\s*#include\s+"submission_policy\.h"\s*$') {
            $body.Add('#include "submission_policy.h"')
            continue
        }
        if ($relativePath -eq "kernels/matmul_api/class_header.inc" -and
            $line -match '^\s*#include\s+"lib/matmul_intf\.h"\s*$') {
            $body.Add('#include "lib/matmul_intf.h"')
            continue
        }
        if ($line -match '^\s*#include\s+[<"].*[>"]\s*$') {
            continue
        }
        $body.Add($line)
    }

    # Some .inc fragments begin inside an open class definition. Preserve
    # their indentation while trimming separator-only newlines.
    $fragmentBody = ($body -join "`n").Trim([char[]]"`r`n")
    $sections.Add("// ===== BEGIN $relativePath =====`n" +
                  $fragmentBody +
                  "`n// ===== END $relativePath =====")
}

$outputDirectory = Split-Path -Parent $OutputPath
New-Item -ItemType Directory -Force -Path $outputDirectory | Out-Null
[System.IO.File]::WriteAllText(
    $OutputPath,
    ($sections -join "`n`n") + "`n",
    [System.Text.UTF8Encoding]::new($false)
)

$policySourcePath = Join-Path $ProjectRoot "tiling/submission_policy.h"
$policyOutputPath = Join-Path $outputDirectory "submission_policy.h"
$policyLines = Get-Content -LiteralPath $policySourcePath | Where-Object {
    $_ -notmatch '^\s*#include\s+"tiling_catalog\.h"\s*$'
}
[System.IO.File]::WriteAllText(
    $policyOutputPath,
    ($policyLines -join "`n") + "`n",
    [System.Text.UTF8Encoding]::new($false)
)

Write-Output "Generated $OutputPath"
Write-Output "Generated $policyOutputPath"
