#!/usr/bin/env python3
"""Portable equivalent of bundle_submission.ps1 for hosts without PowerShell."""

from __future__ import annotations

import argparse
import re
from pathlib import Path


FRAGMENTS = (
    "tiling/tiling_catalog_generated.h",
    "tiling/tiling_types.h",
    "tiling/tiling_catalog.h",
    "tiling/tiling_policy.h",
    "host/acl_runtime.h",
    "host/input_validation.h",
    "host/bm_tiling.h",
    "kernels/reference.asc",
    "kernels/mixed.asc",
    "kernels/kernel_dispatch.asc",
    "kernel.asc",
)

PREAMBLE = '''// Self-contained competition submission bundle.
// Generated by scripts/bundle_submission.ps1; edit the modular sources instead.
#include <algorithm>
#include <cstddef>
#include <cstdint>
#include <atomic>
#include <stdexcept>
#include <string>
#include <vector>
#include "acl/acl.h"
#include "kernel_operator.h"
#include "lib/matmul/matmul_tiling.h"
#include "tiling/platform/platform_ascendc.h"'''  # noqa: E501

INCLUDE_RE = re.compile(r'^\s*#include\s+[<"].*[>"]\s*$')


def bundle(project_root: Path, output_path: Path) -> None:
    sections = [PREAMBLE.rstrip()]
    for relative_path in FRAGMENTS:
        source_path = project_root / relative_path
        if not source_path.is_file():
            raise FileNotFoundError(f"Missing source fragment: {source_path}")

        body: list[str] = []
        skip_local_tuning_entry = False
        for line in source_path.read_text(encoding="utf-8").splitlines():
            if (relative_path == "kernel.asc" and
                    re.match(r"^\s*#ifdef\s+BMMS_ENABLE_TUNING\s*$", line)):
                skip_local_tuning_entry = True
                continue
            if skip_local_tuning_entry:
                if re.match(r"^\s*#endif\s*$", line):
                    skip_local_tuning_entry = False
                continue
            if re.match(r"^\s*#pragma\s+once\s*$", line):
                continue
            if (relative_path == "tiling/tiling_policy.h" and
                    re.match(r'^\s*#include\s+"submission_policy\.h"\s*$', line)):
                body.append('#include "submission_policy.h"')
                continue
            if (relative_path == "kernels/mixed.asc" and
                    re.match(r'^\s*#include\s+"lib/matmul_intf\.h"\s*$', line)):
                body.append('#include "lib/matmul_intf.h"')
                continue
            if INCLUDE_RE.match(line):
                continue
            body.append(line)

        fragment_body = "\n".join(body).strip()
        sections.append(
            f"// ===== BEGIN {relative_path} =====\n"
            f"{fragment_body}\n"
            f"// ===== END {relative_path} ====="
        )

    output_path.parent.mkdir(parents=True, exist_ok=True)
    output_path.write_text("\n\n".join(sections) + "\n", encoding="utf-8")

    policy_source = project_root / "tiling/submission_policy.h"
    policy_output = output_path.parent / "submission_policy.h"
    policy_lines = [
        line for line in policy_source.read_text(encoding="utf-8").splitlines()
        if not re.match(r'^\s*#include\s+"tiling_catalog\.h"\s*$', line)
    ]
    policy_output.write_text("\n".join(policy_lines) + "\n", encoding="utf-8")
    print(f"Generated {output_path}")
    print(f"Generated {policy_output}")


def main() -> None:
    default_root = Path(__file__).resolve().parent.parent
    parser = argparse.ArgumentParser()
    parser.add_argument("--project-root", type=Path, default=default_root)
    parser.add_argument("--output", type=Path,
                        default=default_root / "submission/kernel.asc")
    args = parser.parse_args()
    bundle(args.project_root.resolve(), args.output.resolve())


if __name__ == "__main__":
    main()
