"""Generate the C++ tiling catalog from configs/tiling_candidates.json."""

from __future__ import annotations

import argparse
import json
from pathlib import Path


ROOT = Path(__file__).resolve().parents[1]
SOURCE = ROOT / "configs" / "tiling_candidates.json"
OUTPUT = ROOT / "tiling" / "tiling_catalog_generated.h"


def render() -> str:
    document = json.loads(SOURCE.read_text(encoding="utf-8"))
    candidates = document["candidates"]
    path_names = {"auto_fused": "AUTO_FUSED"}

    lines = [
        "// Generated by scripts/generate_tiling_catalog.py. Do not edit.",
        "#pragma once",
        "#include <cstddef>",
        "#include <cstdint>",
        "",
        "namespace bmms {",
        "",
        "enum class TilingKey : uint32_t {",
    ]
    lines.extend(f'    {item["symbol"]} = {item["key"]},' for item in candidates)
    path_enum_values = [path_names[item["path"]] for item in candidates]
    unique_paths = list(dict.fromkeys(path_enum_values))
    lines.extend([
        "};",
        "",
        "enum class KernelPath : uint8_t { "
        + ", ".join(unique_paths) + " };",
        "",
        "struct StaticTilingConfig {",
        "    TilingKey key;",
        "    const char* name;",
        "    KernelPath path;",
        "    bool implemented;",
        "    uint32_t tileM;",
        "    uint32_t tileN;",
        "    uint32_t tileK;",
        "    uint32_t vecM;",
        "    uint32_t vecN;",
        "    uint32_t splitN;",
        "};",
        "",
        "constexpr StaticTilingConfig kTilingConfigs[] = {",
    ])
    for item in candidates:
        implemented = "true" if item["implemented"] else "false"
        lines.append(
            "    {TilingKey::%s, \"%s\", KernelPath::%s, %s, %d, %d, %d, %d, %d, %d},"
            % (
                item["symbol"], item["name"], path_names[item["path"]], implemented,
                item["tile_m"], item["tile_n"], item["tile_k"],
                item["vec_m"], item["vec_n"], item["split_n"],
            )
        )
    lines.extend([
        "};",
        "",
        "constexpr size_t kTilingConfigCount =",
        "    sizeof(kTilingConfigs) / sizeof(kTilingConfigs[0]);",
        "",
        "}  // namespace bmms",
        "",
    ])
    return "\n".join(lines)


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()
    generated = render()
    if args.check:
        if not OUTPUT.exists() or OUTPUT.read_text(encoding="utf-8") != generated:
            print(f"stale generated file: {OUTPUT}")
            return 1
        return 0
    OUTPUT.parent.mkdir(parents=True, exist_ok=True)
    OUTPUT.write_text(generated, encoding="utf-8", newline="\n")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
